# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Project(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, project_name: str=None, user_name: str=None, json_config: str=None, apk_file: str=None, apk_test_file: str=None, creation_date: str=None):  # noqa: E501
        """Project - a model defined in Swagger

        :param project_name: The project_name of this Project.  # noqa: E501
        :type project_name: str
        :param user_name: The user_name of this Project.  # noqa: E501
        :type user_name: str
        :param json_config: The json_config of this Project.  # noqa: E501
        :type json_config: str
        :param apk_file: The apk_file of this Project.  # noqa: E501
        :type apk_file: str
        :param apk_test_file: The apk_test_file of this Project.  # noqa: E501
        :type apk_test_file: str
        :param creation_date: The creation_date of this Project.  # noqa: E501
        :type creation_date: str
        """
        self.swagger_types = {
            'project_name': str,
            'user_name': str,
            'json_config': str,
            'apk_file': str,
            'apk_test_file': str,
            'creation_date': str
        }

        self.attribute_map = {
            'project_name': 'project_name',
            'user_name': 'user_name',
            'json_config': 'json_config',
            'apk_file': 'apk_file',
            'apk_test_file': 'apk_test_file',
            'creation_date': 'creation_date'
        }
        self._project_name = project_name
        self._user_name = user_name
        self._json_config = json_config
        self._apk_file = apk_file
        self._apk_test_file = apk_test_file
        self._creation_date = creation_date

    @classmethod
    def from_dict(cls, dikt) -> 'Project':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project of this Project.  # noqa: E501
        :rtype: Project
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_name(self) -> str:
        """Gets the project_name of this Project.


        :return: The project_name of this Project.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: str):
        """Sets the project_name of this Project.


        :param project_name: The project_name of this Project.
        :type project_name: str
        """

        self._project_name = project_name

    @property
    def user_name(self) -> str:
        """Gets the user_name of this Project.


        :return: The user_name of this Project.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this Project.


        :param user_name: The user_name of this Project.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def json_config(self) -> str:
        """Gets the json_config of this Project.


        :return: The json_config of this Project.
        :rtype: str
        """
        return self._json_config

    @json_config.setter
    def json_config(self, json_config: str):
        """Sets the json_config of this Project.


        :param json_config: The json_config of this Project.
        :type json_config: str
        """

        self._json_config = json_config

    @property
    def apk_file(self) -> str:
        """Gets the apk_file of this Project.


        :return: The apk_file of this Project.
        :rtype: str
        """
        return self._apk_file

    @apk_file.setter
    def apk_file(self, apk_file: str):
        """Sets the apk_file of this Project.


        :param apk_file: The apk_file of this Project.
        :type apk_file: str
        """

        self._apk_file = apk_file

    @property
    def apk_test_file(self) -> str:
        """Gets the apk_test_file of this Project.


        :return: The apk_test_file of this Project.
        :rtype: str
        """
        return self._apk_test_file

    @apk_test_file.setter
    def apk_test_file(self, apk_test_file: str):
        """Sets the apk_test_file of this Project.


        :param apk_test_file: The apk_test_file of this Project.
        :type apk_test_file: str
        """

        self._apk_test_file = apk_test_file

    @property
    def creation_date(self) -> str:
        """Gets the creation_date of this Project.


        :return: The creation_date of this Project.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: str):
        """Sets the creation_date of this Project.


        :param creation_date: The creation_date of this Project.
        :type creation_date: str
        """

        self._creation_date = creation_date
